fix: compile warning
bitwalker/strukt pull request #15
Opened 2023-08-08 08:11 UTC by tt67wq

fix some compile problem:
```
Compiling 8 files (.ex)
warning: Regex.regex?/1 is deprecated. Use Kernel.is_struct(term, Regex) or pattern match on %Regex{} instead
  lib/validation.ex:81: Strukt.Validation.generate_body/2
```
```
lib/params.ex:103:pattern_match
The pattern can never match the type.

Pattern:
nil

Type:
struct()

________________________________________________________________________________
lib/typespec.ex:99:pattern_match_cov
The pattern
variable_elements

can never match, because previous clauses completely cover the type
[{[any(), ...] | {_, _, _}, [any(), ...] | {_, _, _}}, ...].

________________________________________________________________________________
```

2023-08-08 18:51 UTC, bitwalker requested changes
Thanks for the PR!

There are some seemingly unrelated changes here (commented-out code, etc.) which I'd like to have sorted out before this gets merged. I've left comments where I have questions or would like changes made. Other than that..LGTM

2023-08-08 18:51 UTC, bitwalker commented on lib/params.ex
> +  defp get_struct_field_value(struct, field), do: Map.get(struct, field)
This change introduces a bug: `Map.get/2` will blow up if `struct` is `nil`, which is why the original code matches `struct` defensively first.

2023-08-08 18:51 UTC, bitwalker commented on lib/typespec.ex
> +  # defp map(elements) when is_map(elements),
Why is this commented out?

2023-08-08 18:51 UTC, bitwalker commented on lib/validation.ex
> +              is_struct(data_or_opts, Regex) ->
👍

2023-08-08 18:51 UTC, bitwalker commented on mix.exs
> +      {:dialyxir, "~> 1.3", only: [:dev], runtime: false},
I'd prefer changes like this to be in their own PR, but it's fine this time

2023-08-14 14:21 UTC, tt67wq commented
Thank you for your code review work. It seems that I still have many areas to consider carefully. Please close this pull request for now. I will test it thoroughly.

2023-08-14 14:23 UTC, closed without merging